name: freeciv # you probably want to 'snapcraft register <name>'
base: core20
version: '3.0.3'
summary: Single-line elevator pitch for your amazing snap # 79 char long summary
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict

compression: lzo

parts:
  freeciv:
    plugin: autotools
    source: https://github.com/freeciv/freeciv.git
    source-tag: R3_0_3
    autotools-configure-parameters:
      - --prefix=/usr
      - --enable-shared
      - --disable-static
      - --disable-rpath
      - --disable-dependency-tracking
      - --enable-fcdb=sqlite3
      - --enable-ipv6=yes
      - --enable-patient-connect=yes
      - --enable-mapimg=magickwand
      - --disable-json
      - --enable-client=gtk3.22
      # - --enable-client=gtk3.22,qt
      - --enable-gitrev
      - --enable-debug=no
      - --enable-sdl-mixer=sdl2
      - --enable-fcmp=gtk3
      # - --enable-fcmp=gtk3,qt
      - --enable-sys-lua
      - --with-readline
      - --with-libbz2
      - --with-liblzma
      - CXXFLAGS="-Os"

    build-packages:
      - libsqlite3-dev
      - libmagickwand-6.q16-dev
      - libcurl4-gnutls-dev
      - libsdl2-dev
      - libsdl2-mixer-dev
      - libgtk-3-dev
      # - qtbase5-dev
      - libreadline-dev
      - liblua5.3-dev

    stage-packages:
      - libsqlite3-0
      - libmagickwand-6.q16-6
      - libcurl4
      - libcurl3-gnutls
      - libsdl2-2.0-0
      - libsdl2-mixer-2.0-0
      - libgtk-3-0
      # - libqt5gui5
      # - libqt5widgets5
      - libreadline8
      - liblua5.3-0

apps:
  freeciv-gtk:
    extensions: [gnome-3-38]
    command: usr/bin/freeciv-gtk3.22
    environment:
      FREECIV_DATA_PATH: $SNAP/usr/share/freeciv/
    plugs:
      - audio-playback
      - pulseaudio
      - network-bind
      - home

  # freeciv-qt:
  #   extensions: [gnome-3-38]
  #   command: opt/freeciv/bin/freeciv-qt
  #   environment:
  #     PATH: "$PATH:/opt/freeciv/bin"
  #   plugs:
  #     - audio-playback
  #     - pulseaudio
  #     - network-bind
  #     - home
